export const FETCH_TEXTS_DB = "FETCH_TEXTS_DB";
export const MODAL_TOGGLE = "MODAL_TOGGLE";
export const SET_TEXT_DETAILS = "SET_TEXT_DETAILS";
export const RENDER_OLD_TEXT = "RENDER_OLD_TEXT";
export const SET_USER_LOGIN = "SET_USER_LOGIN";
export const SET_STORE_VARIABLE = "SET_STORE_VARIABLE";
export const FETCH_NOTES_CATEGORIES = "FETCH_NOTES_CATEGORIES";
